### ISSUE TITLE
Any way to make it work for React 17 ?

### ISSUE THREAD

**Issue by s-bose** [OvidijusParsiunas/active-table#2]
Hi.
The `active-table-react` package works fine on a React 17 project but the `package-lock.json` lists its dependency being react 18. I there any way to make that dependency fixed?

**Comment by OvidijusParsiunas** [comment]
Hi @s-bose, I'm trying to understand the nature of your problem. Do you mean that your project is importing two react libraries: 17 and 18? Hence, is the issue itself the matter of resultant project size due to two react packages or are there errors on your end. Any information to help me understand this better will help, thankyou!

**Comment by s-bose** [comment]
Hello. What I'm trying to say is that when installing `active-table-react` in a react 17 project it works just as intended except the `active-table-react` package in my project's `node_modules` has also installed its own react package inside its own `node_modules`. It is not messing up the main react 17 in my project but can you please make the react dependency a peer dependency? Maybe that would fix it?
Apologies for the confusion. I'm comparatively new to the react ecosystem.

**Comment by OvidijusParsiunas** [comment]
Ok, so to my understanding its a two React library problem?

**Comment by OvidijusParsiunas** [comment]
Yep, I'll investigate to find the best solution

**Comment by s-bose** [comment]
Thanks mate. Cheers!

**Comment by OvidijusParsiunas** [comment]
Just to note, once I do have the solution, I'll need to fully test it out across which may take some time. I should have this all settled in 1-2 hours, I'll report on my progress in this thread.

**Comment by s-bose** [comment]
No worries at all. I would be more than happy to help if you need anything

**Comment by OvidijusParsiunas** [comment]
As per your suggestion, I have used the ```peerDependencies``` property to set the allowed `react` versions as follows:
`"react": ">=17.0.1 || >=18.0.0"`.

This is available in the `0.0.15` version of the `active-table-react` package. The reason why I used the minimum version of  `17.0.1` and not `17.0.0` is because that is the minimal minor/patch version being used by the [@lit/labs-react](https://www.npmjs.com/package/@lit-labs/react) library which this package is using as a wrapper to work in react - [reference here](https://github.com/lit/lit/blob/1b42ec94c59b8d578529c411c46c1023f05f9a3d/packages/labs/react/package.json#L155).

Technically, web components should be supported by React version 16, however I am getting a variety of issues for it and will continue investigating a little further to see if I can get it to work for that. Nevertheless, it should be working fine for 17 and 18 :)

Thanks again, I would have not been able to do this without your help!

**Comment by OvidijusParsiunas** [comment]
I believe this concludes the work for this issue, nevertheless if you believe something may need to be changed feel free to comment below and reopen this thread :)

Once again, thankyou very much for raising the issue and letting me know about this fantastic optimization opportunity!

Just to note, the official release date for this component will be at the end of this month or the start of next, hence why the component is using the `0.0.x` version increments. If you find any bugs or have suggestions for improvements, DO NOT HESITATE to raise new issues and I will be very happy to discuss them accordingly :)

Thanks again! 💯

**Comment by s-bose** [comment]
Thank you so much for responding so fast and taking my thoughts into consideration. Appreciate the effort! 💯
