### ISSUE TITLE
Filter not working when setting it as an attribute in sveltekit

### ISSUE THREAD

**Issue by tugbrandsapps** [OvidijusParsiunas/active-table#23]
When adding filter="true" to the active-table element in my sveltekit app, or a filter with an object or array of objects, it breaks the table.  It should also be noted that the same thing happens on your sveltekit repo at https://codesandbox.io/p/sandbox/active-table-sveltekit-forked-fy9wlf

**Comment by OvidijusParsiunas** [comment]
Hi @tugbrandsapps.
Can you try to use the curly braces syntax like: `filter={true}` to see if it works for you. Thanks!

**Comment by tugbrandsapps** [comment]
Yes, it does work.  I would say it is a little confusing to know when we can send in an object directly and when it must be stringified.

**Comment by OvidijusParsiunas** [comment]
We usually recommend setting values as [properties](https://javascript.info/dom-attributes-and-properties#dom-properties) rather than [attributes](https://www.w3schools.com/html/html_attributes.asp) when you are using a framework. In the Svelte case - that would be using the `{}` syntax rather than `""`.

 Hopefully this helps.

**Comment by OvidijusParsiunas** [comment]
I will close this issue since the original problem has been resolved. If you have any further queries relating to this matter, feel free to comment below. For anything else you are more than welcome to raise a new issue.
Thanks!
