### ISSUE TITLE
Searching select box

### ISSUE THREAD

**Issue by dmiric** [OvidijusParsiunas/active-table#25]
I would like to suggest a feature. When you have a select as a field type to be able to type and filter options.

**Comment by OvidijusParsiunas** [comment]
Hi. This feature has been suggested in the following [issue](https://github.com/OvidijusParsiunas/active-table/issues/8). Due to my current commitments in this and other projects I unfortunately do not have the time to prioritise this feature, however I may consider adding it in the future. Thankyou!
