### ISSUE TITLE
Using active-table in a Flask app

### ISSUE THREAD

**Issue by umayrh** [OvidijusParsiunas/active-table#28]
Hi,

I'm trying to use active-table in my Flask app by including the [JS bundle](https://unpkg.com/active-table@1.1.2/dist/activeTable.bundle.js) in my HTML code but I get the following error:

```
activeTable.bundle.js:870 Uncaught SyntaxError: Unexpected token 'export' (at activeTable.bundle.js:870:10591)
```

Any idea why?

**Comment by OvidijusParsiunas** [comment]
Hi @umayrh.
Are you trying to use Server Side Rendering? Active Table is a web component, which will inherently have issues if you are trying to render it on the server.
I've personally never used Flask for generating websites, could you perhaps share some code that I could use to run it on my flask app?
It would be awesome if you could maybe upload your app onto a GitHub repository so that I could clone it and see if I can run it on my computer when I get home tonight.
Thankyou for any details!

**Comment by umayrh** [comment]
Hi @OvidijusParsiunas ,

Appreciate your quick response. I figured out the problem. I was using:

```
<script src="https://unpkg.com/active-table@1.1.2/dist/activeTable.bundle.js"></script>
```

instead of

<script type="module" src="https://unpkg.com/active-table@1.1.2/dist/activeTable.bundle.js"></script>

I've also been able to get another editable data table, [Tabulator](https://tabulator.info/ ), to work but I'd prefer to use active-table because of its look-and-feel and ability to easily add rows and columns. Fingers crossed :)

-U

**Comment by OvidijusParsiunas** [comment]
Happy this worked for you @umayrh!
