### ISSUE TITLE
navigator is not defined when using with NextJs

### ISSUE THREAD

**Issue by sarah-vo19** [OvidijusParsiunas/active-table#37]
Hi @OvidijusParsiunas,
Your library is awesome and I'm using it in my NextJs project. I got this error and I'm not sure if it's the error from my side or the library. The table works on the UI but I still got this error:
<img width="606" alt="image" src="https://github.com/OvidijusParsiunas/active-table/assets/155673090/6c168954-61be-409d-bec2-e537f09af981">

**Comment by sarah-vo19** [comment]
Thank you so much I definitely imported it wrong. The error is gone now. If possible can I ask you too this too?

So in my case, I need to load data from the database and put them in the table, what I understood from the documentation is that I have to use ref to do that, is there anyway I can achieve it using react state? Thank you
<img width="407" alt="image" src="https://github.com/OvidijusParsiunas/active-table/assets/155673090/9132f47e-3698-447b-8179-8b89c36d5a99">

**Comment by OvidijusParsiunas** [comment]
Could you elaborate a little on what you mean by using React state?

The code example you have shown looks good!

May I also ask if you could possibly create a new issue and we can further discuss this matter there to help future readers navigate to issues that are relevant to them.

Thankyou!

**Comment by sarah-vo19** [comment]
Thank you for your response, I've just realized you're using ref so that the table can be used in as many framework as possible. I'll create a new issue asking about the flickering I'm facing. Thanks again

**Comment by OvidijusParsiunas** [comment]
Hey @sarah-vo19. You are correct, I used `tableElementRef ` in my examples in order to provide the most vanilla way of applying property values to the component as it is pretty much the same across all the frameworks. However directly _inlining_ properties and obtaining a reference for the component vary across different frameworks, that's why developers are recommended to checkout the [Example Frameworks](https://activetable.io/examples/frameworks) section to get some insight for their framework of choice :)

If the original question has been answered I will close this issue. Feel free to raise a new issue for anything else.
