### ISSUE TITLE
Table becomes laggy when displaying a long table

### ISSUE THREAD

**Issue by sarah-vo19** [OvidijusParsiunas/active-table#38]
Hi @OvidijusParsiunas, I tried using Activetable with NextJs to display a really long table (around 1000 lines) and the scrolling experience is laggy + my browser freezes after a minute or two. Do you have any advice on how to tackle this problem? Thanks

This is a sandbox example: https://codesandbox.io/p/sandbox/active-table-react-xlsx-forked-5z7y65?file=%2Fsrc%2Findex.tsx
You can try uploading this file and you'll see the UI become frozen: 
[mock long data.csv](https://github.com/OvidijusParsiunas/active-table/files/14828157/mock.long.data.csv)

https://github.com/OvidijusParsiunas/active-table/assets/155673090/92138375-e663-46a8-ae06-12dbbe2f8693

**Comment by OvidijusParsiunas** [comment]
Hi @sarah-vo19. Thankyou for describing the problem and sending a video to help illustrate it.

I believe the laggyness/stutterring is caused by the fact that constructing editable cells is a little more complex over a static cells - mostly to due to the addition of [_event listeners_](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener).

As much as I would love to try and optimize it, I believe this is an unfortunate performance cap that comes with editable tables (where all cells are editable), hence I don't think I can really do much more to make it more performant.
If I get more time in the future, I would like to investigate this further, but the result will likely remain similar. My apologies.
