### ISSUE TITLE
Validate file integrity

### ISSUE THREAD

**Issue by sbachiller** [OvidijusParsiunas/active-table#5]
Currently, the import functionality allows users to import various types of files when uploading data. I propose implementing a file type control feature to restrict users to upload only CSV files. 

The proposed solution would involve adding a file type validation function that checks the uploaded file's format before processing it. If the uploaded file is not a CSV file, the importCSV function will return an error in order to control the error and improve the user experience

Thank you for considering this proposal.

**Comment by OvidijusParsiunas** [comment]
The input element which opens up the file browser for `importCSV` method and the `import` button in `csvButtons` has been set up to only accept `.csv` format files ([code here](https://github.com/OvidijusParsiunas/active-table/blob/a403122911fe140e75192e61a74f40d592a8cdbb/component/src/elements/CSV/importButton/CSVImportButtonElement.ts#L11)). 

Are you still able to import non `csv` file formats? If so, may I ask if you are able to see them in your file manager before confirming the upload. And what kind of an operating system you are running on? (A screenshot would also be great!)

**Comment by sbachiller** [comment]
Even though the input element only accepts .csv files, you can change the selector in the file manager and import, for example a png file:

![imagen](https://user-images.githubusercontent.com/1898425/228786936-8931dd20-ff0a-475d-8446-65ee14b3a34c.png)

**Comment by OvidijusParsiunas** [comment]
I see what you mean. I did some more research on this and there is no bullet proof way to prove that the uploaded file is technically CSV. Aside from narrowing down the available file selection by extension, the code can also check the first couple of bytes of the uploaded file to see if they correspond to characters that are common for CSVs like "ID" and "EF", however these are not standardised and there can be scenarios where these characters are not present in valid CSVs. Hence, I could be invalidating valid cases.

Unfortunately, the bottom of the line is that if users are uploading .csv files that have incorrect binary properties, it has to be up to them to fix on their end as there is no ultimate technical solution.

Just another two cents from a security perspective: because this is a web component that runs entirely on the client side, the JavaScript can always technically be manipulated and if someone deliberately wants to upload a non valid CSV, they will always be able to. Hence, the component can only do its best to narrow down the file selection for their convenience.

Hope this makes sense and I appreciate your concern!

**Comment by OvidijusParsiunas** [comment]
I am closing this issue as it will not be pursued any further for the time being.
