### ISSUE TITLE
Feature: data filtering

### ISSUE THREAD

**Issue by sbachiller** [OvidijusParsiunas/active-table#8]
Hi there (again :D)

I am writing to request a new feature, specifically, I am interested in having the ability to add a filter to the select columns, allowing users to search for specific options in the dropdown list.

As it stands, the select columns are incredibly useful, but they can become unwieldy when there are many options to choose from. Having a filter would make it much easier for users to quickly locate the options they need.

Thank you for your time and consideration.

Thks :smiley:

**Comment by OvidijusParsiunas** [comment]
Hi @sbachiller, a filter feature is currently on this project's roadmap and is something that I am planning to do in the very near future. Unfortunately because it involves quite a few changes in the code - its priority has been shifted back by smaller changes that are important to get out of the way first before we announce the official release for active-table.

I cannot set an exact date for when this feature will be added as it could range between the next month to the one after, but it is one of the next big features I will be working on (and I will try to prioritise this over others). I will add updates to this issue when I will be working on this to keep you up to date.

Once again, @sbachiller thankyou very much for being one of the early adapters of active-table and your feedback is always appreciated!!

**Comment by OvidijusParsiunas** [comment]
I will temporarily close this issue and reopen it when working on the feature. Thanks!

**Comment by OvidijusParsiunas** [comment]
@sbachiller I just re-read your first comment, and wanted to double check what you meant by your request in-case I have misunderstood something. Were you looking for a feature that would allow the user to select the columns that are displayed, or a feature that would filter rows based on certain text in a column?

**Comment by OvidijusParsiunas** [comment]
This feature is supported from component version 0.3.5. Please read [here](https://activetable.io/docs/filter) for more information.

**Comment by sbachiller** [comment]
Hi! Sorry for the delay. What I meant was, in the select column types, add a filter in order to search through the options. Sorry and thank you.

**Comment by OvidijusParsiunas** [comment]
Ohhhhhhh I see what you mean now. Ok, that is an interesting feature! I have currently prioritised a few other features at the moment (as well as work in other projects) but I will definitely consider adding it in the future! Thankyou very much for this great suggestion!

**Comment by OvidijusParsiunas** [comment]
Hey @sbachiller, I was wondering if instead of filtering the options, could the users gain some benefit if they were automatically sorted in an alphabetical order? Which should help them find the option they are looking for quicker.

**Comment by OvidijusParsiunas** [comment]
Alphabetical sorting was something that I could have implemented quickly, but if it doesn't yield that much of a benefit I will look into other approaches.

Typeahead is a really interesting idea! It could be the one.

I was wondering if there are any examples that you may have come across which offer the UX you are looking for, it may help decide on the best approach for filtering options.

If you have't don't worry, as it will take a bit of time before I can tackle this, but it would of course be great to have a concrete goal when starting work on this! Let me know if anything pops up!
